[project]
name = "mcp-server-with-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.14",
    "mcp[cli]>=1.10.1",
    "uvicorn>=0.35.0",
]
